### ISSUE TITLE
能加入其它计时器吗？比如午休提醒

### ISSUE THREAD

**Issue by zhonghuaifang** [Williamlifetime/work-timer#3]
中午吃饭去晚了人太多

**Comment by Williamlifetime** [comment]
感谢你的使用和建议~预计在下一版本开发计划中加入🙌

**Comment by Williamlifetime** [comment]
午休提醒功能已上线~欢迎更新下载体验✨
https://marketplace.visualstudio.com/items?itemName=WilliamMa.work-timer
