### ISSUE TITLE
可以自定义上下班时间吗

### ISSUE THREAD

**Issue by guaiguaiguo** [Williamlifetime/work-timer#6]

**Comment by Williamlifetime** [comment]
抓到了  不认真读readme星人！！

目前插件是具有此功能的哦

**插件设置**
有两种插件设置的方案，下面两种选其一就可以啦   所有功能都可以在菜单中找到相关设置项
1. Ctrl + Shift + P 打开命令行输入 打工计时器 进入设置菜单
2. 点击右下角状态栏中的计时器，打开设置菜单

**Comment by Williamlifetime** [comment]
🧎我忽略了大家的上班时间可能不一致的问题，之前的版本中只能针对午休&下班时间进行设置调整，并未考虑设计到上班时间可能不一致的问题。上班时间无法自定义的问题将在下个版本中得到解决～
感谢您的建议～respect
