### ISSUE TITLE
缓存数据频繁触发同步

### ISSUE THREAD

**Issue by 0x2710-10000** [Williamlifetime/work-timer#7]
缓存的时间及喝水数据等频繁改动的数据存储在settings.json中，会频繁触发数据同步，体验不太好，望更新

**Comment by Williamlifetime** [comment]
已修复 持续工作系数算法缺陷导致反复弹窗提示喝水数据 的异常问题～
修复版本已发布～
🙏感谢反馈
[VS Marketplace](https://marketplace.visualstudio.com/items?itemName=WilliamMa.work-timer)
